### PR TITLE
Office hours

### PR DESCRIPTION
**Pull request by lawtlee**
This is an enhancement or feature.

## Summary

Added in-person office hours to the contact section. May look a little wonky, can fix the styling if needed.

image

## Context

No, it is an additional feature

### CODE REVIEW

**Comment by emilygong-zhuying** [comment]
Thanks for the quick update! I have 2 comments 🥹
1. center align vertically for each cell (at the moment they're top aligned)
2. there's a weird spacing within each row where there's more space on the bottom than the top. I hope that makes sense... Could you fix that as well?
3. Can you change the text to Walk-in DataSquad Hours \n (no appointment needed)
Please message me if you need more clarification! Thanks @lawtlee :))

**Comment by lawtlee** [comment]
Does this work?
image

**Comment by emilygong-zhuying** [comment]
looks great overall - i have 2 minute details but could you
1. center align `Times` with the rest of the text in the column
2. change the text from `Walk in DataSquad Hours \n (no appointment needed)` and `We are located in Room 21536 in YRL` to `Walk-in DataSquad Hours in YRL Room 21536 \n (no appointment needed)` and make it the same style as the current blue text (i.e. smaller font, not italicized, and blue)

Feel free to pull request again once you're done or just merge everything yourself! I think it looks great :)) Thanks!

**Comment by lawtlee** [comment]
The "Times" is already center formatted, if I add specific padding adjustments it doesn't necessarily translate very well when the viewport width changes from 1440.
image
image

**Pull request merged**
